### ISSUE TITLE
Complete Rubygem/Travis configuration

### ISSUE THREAD

**Issue by mbbroberg** [sensu-plugins/sensu-plugins-sendgrid#1]
We build this plugin due to the request of https://github.com/sensu-plugins/community/issues/96 

It's not yet ready to build. Once ready, an Org Maintainer will need to complete step 8 in our "Add a repository" process: `Add Rubygems deploy key to .travis.yml`

**Comment by majormoses** [comment]
closed in https://github.com/sensu-plugins/sensu-plugins-sendgrid/commit/64cf37699267e60a12edbea089e9a572fa8ea5ff
